/**
 * Generates TypeScript declaration files for .mdma templates.
 *
 * For a template at `foo.mdma`, the declaration is written to
 * `foo.d.mdma.ts` — the name TypeScript resolves for `import x from
 * "./foo.mdma"` when `allowArbitraryExtensions` is enabled. The import is
 * then typed as `ParsedTemplate<{...}>` matching the template's `@inputs`,
 * so mismatched inputs objects are flagged at compile time.
 */

import { parseFile } from "./fileParser.js";
import type { InputDecl, ScalarType } from "./model.js";

const TS_SCALARS: Record<ScalarType, string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
  object: "Record<string, unknown>",
};

function tsTypeFor(decl: InputDecl): string {
  if (decl.type.endsWith("[]")) {
    return `${TS_SCALARS[decl.type.slice(0, -2) as ScalarType]}[]`;
  }
  return TS_SCALARS[decl.type as ScalarType];
}

/** The declaration-file path for an .mdma file: `foo.mdma` -> `foo.d.mdma.ts`. */
export function dtsPathFor(mdmaPath: string): string {
  return mdmaPath.replace(/\.mdma$/, ".d.mdma.ts");
}

/**
 * Generate the `.d.mdma.ts` content for an .mdma source string.
 *
 * Inputs with a declared default become optional properties. A template with
 * no inputs is typed `Record<string, never>` so passing any input is an
 * error. Throws `MdmaSyntaxError` if the source does not parse.
 */
export function generateDts(source: string, options: { moduleName?: string } = {}): string {
  const moduleName = options.moduleName ?? "typescript-mdma";
  const inputs = parseFile(source).inputs;

  let shape: string;
  if (inputs.length === 0) {
    shape = "Record<string, never>";
  } else {
    const fields = inputs.map(
      (decl) => `  ${decl.name}${decl.hasDefault ? "?" : ""}: ${tsTypeFor(decl)};`
    );
    shape = `{\n${fields.join("\n")}\n}`;
  }

  return [
    "// Generated by mdma-typegen. Do not edit.",
    `import type { ParsedTemplate } from "${moduleName}";`,
    "",
    `declare const template: ParsedTemplate<${shape}>;`,
    "export default template;",
    "",
  ].join("\n");
}
